service: eddie-backendChallenge
useDotenv: true
provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  stage: api
  region: us-west-2
  environment:
    ACCESS_TOKEN: ${env:AWS_ACCESS_KEY_ID}
    SECRET_KEY: ${env:AWS_SECRET_ACCESS_KEY}
package:
  #exclude all files except production main.go file which is defined in build directory
  patterns:
    - '!./**'
    - ./build/**
functions:
  app:
    handler: build/main
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
resources:
  Resources:
    DeviceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Device
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S

        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 4
          WriteCapacityUnits: 4