service: eddie-backendChallenge
provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  stage: api
  region: us-east-1
  environment:
    ACCESS_TOKEN: ${env:ACCESS_KEY_ID}
    SECRET_KEY: ${env:SECRET_ACCESS_KEY}

package:
  patterns:
    - '!./**'
    - ./build/**

functions:
  app:
    handler: build/main
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Device
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
          - AttributeName: note
            AttributeType: S
          - AttributeName: serial
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 4
          WriteCapacityUnits: 4