// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	domain "challenge/domain"
	errors "challenge/lib/errors"

	mock "github.com/stretchr/testify/mock"
)

// DeviceRepository is an autogenerated mock type for the DeviceRepository type
type DeviceRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: device
func (_m *DeviceRepository) Create(device *domain.Device) (*domain.Device, *errors.AppError) {
	ret := _m.Called(device)

	var r0 *domain.Device
	if rf, ok := ret.Get(0).(func(*domain.Device) *domain.Device); ok {
		r0 = rf(device)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Device)
		}
	}

	var r1 *errors.AppError
	if rf, ok := ret.Get(1).(func(*domain.Device) *errors.AppError); ok {
		r1 = rf(device)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *DeviceRepository) FindById(id string) (*domain.Device, *errors.AppError) {
	ret := _m.Called(id)

	var r0 *domain.Device
	if rf, ok := ret.Get(0).(func(string) *domain.Device); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Device)
		}
	}

	var r1 *errors.AppError
	if rf, ok := ret.Get(1).(func(string) *errors.AppError); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}

	return r0, r1
}
